### PR TITLE
Switch to rund, saves almost a second on first invocation of build.d

### PR DESCRIPTION
**Pull request by marler8997**
```
$ rm -rf /tmp/.rdmd-*/
$ time rdmd --build-only ./src/build.d

real	0m3.245s
user	0m2.763s
sys	0m0.487s
$ rm -rf /tmp/.rund-*/
$ time rund --build-only ./src/build.d

real	0m2.416s
user	0m2.070s
sys	0m0.346s
```

### CODE REVIEW

**Comment by wilzbach** [comment]
You are still using the Makefile on Travis.

**Comment by marler8997** [comment]
Yeah, is build.d ready?

**Comment by wilzbach** [comment]
It's tested on CircleCi at upstream DMD for a few months now. However, it doesn't fully support Windows yet (though neither does the Makefile).

**Comment by marler8997** [comment]
Look like using `rund` saved about half a second when running `./src/build.d` on travis.  7 seconds with `rdmd`, 6.5 seconds with `rund`, though, most of that time is actually building the compiler rather than `build.d`.

**Pull request merged**
